packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@eslint/js': latest
  '@arco-design/web-vue': latest
  '@tailwindcss/vite': latest
  '@vitejs/plugin-vue': latest
  '@types/node': ^24
  echarts: latest
  eslint: latest
  eslint-config-prettier: latest
  eslint-plugin-vue: latest
  globals: latest
  pinia: latest
  tailwindcss: latest
  typescript: ^5
  typescript-eslint: latest
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  vue-eslint-parser: latest
  vue: latest
  vue-router: latest
  vue-tsc: latest
  prettier: ^3.8.3
  cspell: ^10.0.0
  sass: ^1.99.0
  stylelint: ^17.11.1
  stylelint-config-standard-scss: ^17.0.0
  stylelint-config-standard-vue: ^1.0.0
  postcss-html: ^1.8.1
  postcss-sass: ^0.5.0
  postcss-scss: ^4.0.9
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  '@parcel/watcher': false
